# Generated by Django 5.1.4 on 2025-01-17 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breiflyplatform', '0004_summary_user_alter_user_table_accountinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsetting',
            name='search_description',
            field=models.CharField(default='Default search description', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountinformation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
