# Generated by Django 5.1.4 on 2025-01-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breiflyplatform', '0005_searchsetting_search_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsetting',
            name='keywords',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='searchsetting',
            name='search_description',
            field=models.TextField(),
        ),
    ]
