# Generated by Django 5.1.4 on 2025-01-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breiflyplatform', '0006_searchsetting_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previoussearch',
            name='search_descriptopm',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchsetting',
            name='keywords',
            field=models.TextField(),
        ),
    ]
