# Generated by Django 5.1.4 on 2025-01-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breiflyplatform', '0008_rename_search_descriptopm_previoussearch_search_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previoussearch',
            old_name='search_descriptions',
            new_name='search_description',
        ),
    ]
