# Generated by Django 5.1.4 on 2025-01-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breiflyplatform', '0009_rename_search_descriptions_previoussearch_search_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='previoussearch',
            name='search_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_searches', to='breiflyplatform.searchsetting'),
        ),
    ]
