# Generated by Django 5.1.4 on 2025-01-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breiflyplatform', '0010_previoussearch_search_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previoussearch',
            name='search_setting',
            field=models.ForeignKey(blank=True, db_column='search_settings_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_searches', to='breiflyplatform.searchsetting'),
        ),
    ]
