# Generated by Django 5.1.4 on 2025-01-20 05:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breiflyplatform', '0011_alter_previoussearch_search_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='language',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='report_time',
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='company_brief',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='content_sentiment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='industry',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='recent_ventures',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='accountinformation',
            name='target_audience',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchsetting',
            name='type_of_search',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ScheduledSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_execution', models.DateField()),
                ('time_of_execution', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_settings', models.ForeignKey(db_column='search_settings_id', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_searches', to='breiflyplatform.searchsetting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_searches', to='breiflyplatform.user')),
            ],
            options={
                'db_table': 'scheduled_search',
            },
        ),
    ]
