# Generated by Django 5.1.4 on 2025-01-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breiflyplatform', '0013_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountinformation',
            name='account_version',
            field=models.CharField(default='', max_length=35),
        ),
    ]
