# Generated by Django 5.1.4 on 2025-01-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breiflyplatform', '0014_accountinformation_account_version'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='"auth"."users"',
        ),
    ]
